afgan station: sex update
TheWayYouLOOKATME/Space-Afgan-14 pull request #4
Opened 2024-07-29 12:52 UTC by Uhboer

afgan station: sex update
* добавлен ПП Люти там звуки для него и всё такое
* добавлен ПП МП9 евил ган там звуки для него и всё такое
* добавлена униформа и маска хамаса
* добавлена музыка в лобби
* добавлены тайлы песка
* добавлен кактус
* добавлены запчасти для МП9 евил ган
* добавлены 2 магазина на ПП
* добавлены запчасти для ПП
* добавлен крафт ПП МП9
* добавлен калибр 9мм

2024-07-29 13:08 UTC, TheWayYouLOOKATME requested changes
- [x] Перенос в Audio/Afgan/Weapons

2024-07-29 13:10 UTC, TheWayYouLOOKATME requested changes
- [x] Перенос в Prototypes/Afgan/Clothing

2024-07-29 13:11 UTC, TheWayYouLOOKATME requested changes
- [ ] Перенос в Prototypes/Afgan/Misc

2024-07-29 13:23 UTC, TheWayYouLOOKATME requested changes
**Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/pistol.yml
Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/pistol.yml
Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/pistol.yml
Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml**
- [x] Перенос в Prototypes/Afgan/Weapons/Projectiles
- [ ] Перенос в Prototypes/Afgan/Weapons/Ammunition
- [x] Перенос в Prototypes/Afgan/Weapons

2024-07-29 13:23 UTC, TheWayYouLOOKATME commented
Делой давай @Uhboer 

> 
![image](https://github.com/user-attachments/assets/6fb45856-3eea-45a0-a2a3-55ba7fba71c8)

2024-08-13 16:22 UTC, theresdotsinmyname commented
### Im tired🤨

2024-08-13 16:22 UTC, merged